import AdvCloudIndex from 'views/advcloud/AdvCloudIndex.jsx';

var routes = [
    {
        path: '/index',
        name: 'Dashboard',
        icon: 'fa fa-bar-chart text-advcloud',
        component: AdvCloudIndex,
        layout: '/advcloud',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Cadastro de pessoas',
        icon: 'fa fa-user-plus text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Ficha do boneco',
        icon: 'fa fa-file-text text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Processos',
        icon: 'fa fa-archive text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Benefícios',
        icon: 'fa fa-handshake-o text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Agendas',
        icon: 'fa fa-calendar text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Publicações',
        icon: 'fa fa-pencil-square text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Veículos',
        icon: 'fa fa-car text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Relatórios',
        icon: 'fa fa-files-o text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Configurações de ambiente',
        icon: 'fa fa-cog text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Tarefas',
        icon: 'fa fa-bookmark text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Modelos',
        icon: 'fa fa-book text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Comunicação',
        icon: 'fa fa-comments text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'Sistema PUSH',
        icon: 'ni ni-tv-2 text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
    {
        path: '/index',
        name: 'SAC',
        icon: 'fa fa-phone-square text-advcloud',
        component: AdvCloudIndex,
        layout: '/dashbord',
        classTipo: 'advcloud',
    },
];

export default routes;